# Image dasar: Nginx varian alpine (kecil, ~20 MB)
FROM nginx:alpine

# Salin halaman web ke direktori default Nginx
COPY index.html /usr/share/nginx/html/index.html

# Dokumentasi: Nginx melayani di port 80
EXPOSE 80
